# Generated by Django 3.0.2 on 2020-01-18 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.TextField(default='no value'),
            preserve_default=False,
        ),
    ]
